
version: "3"
services:
  mysql8.0:
    image: mysql:8.0
    container_name: kodilla_mysql_container_trello
    ports:
      - 3380:3306
    environment:
      - MYSQL_DATABASE=kodilla_database
      - MYSQL_USER=kodilla_user
      - MYSQL_PASSWORD=kodilla_password
      - MYSQL_ROOT_PASSWORD= admin
    volumes:
      - ./my.cnf:/root/.my.cnf:ro
      - ./mysql8.0/conf.d:/etc/mysql/conf.d:ro
      - ./mysql8.0/logs:/var/log/mysql:rw
      - ./mysql8.0/initdb.d:/docker-entrypoint-initdb.d:ro
      - ./auto-generate:/auto-generate:rw